spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sakila?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: wsp25314
    driver-class-name: com.mysql.cj.jdbc.Driver