version: "3"
services:
  mysql:
    container_name: mysql
    build:
     context: .
     dockerfile: dbDockerfile
    hostname: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./mysql_data:/var/lib/mysql
    - ./mysql_db.cnf:/etc/mysql/conf.d/mysql_db.cnf
    expose:
    - "3306"
    networks:
    - "c7nNetwork"
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
    - "c7nNetwork"
    ports:
    - "6379:6379"
  web:
    container_name: web
    build:
     context: .
     dockerfile: Dockerfile
    hostname: web
    expose:
    - "8080"
    ports:
    - "8080:8080"
    networks:
    - "c7nNetwork"
    links:
    - mysql
    - redis
networks:
  c7nNetwork:
    driver: bridge